prefix = "./data"
stop-words = "./data/lemur-stopwords.txt"
dataset = "faculty"
corpus = "line.toml"
index = "./data/idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"


